### ISSUE TITLE
How to use ums with docker?

### ISSUE THREAD

**Issue by tr15tan** [UniversalMediaServer/UniversalMediaServer#1841]
I just downloaded the latest ums docker image from the universalmediaserver repository, but i can't find out what to do next. I run the image without other parameters and nothing happened except the log 'Universal Media Server is now available for renderers to find' shown in the terminal. This is my first time to try ums and docker, and there seems no introduction about how to use the image? Please give me some instructions about this kind of situation, thanks.

ps. My pc os is ubuntu 16.04, and the target device is PS4.
I noticed there is another user encountered this issue in https://www.universalmediaserver.com/forum/viewtopic.php?f=9&t=13769&p=40078&hilit=docker#p40078

**Comment by atamariya** [comment]
Try it like:
`
docker run -it -v /Docker/ums:/profile -v /Media:/media --net host ums
`

**Comment by tr15tan** [comment]
> Try it like:
> `docker run -it -v /Docker/ums:/profile -v /Media:/media --net host ums`

Hi atamariya:
thanks for the reply, I tried the above command and the output is bellow
```
tristan@tristan-home:~$ sudo docker run -it -v /Docker/ums:/profile -v /Media:/media --net host universalmediaserver/ums
[sudo] tristan 的密码： 
WARN  19:21:20.278 [main] Can't load neither /root/.config/UMS/UMS.conf: Unable to load the configuration from the URL file:/root/.config/UMS/UMS.conf nor /etc/skel/.config/UMS/UMS.conf: Unable to load the configuration from the URL file:/etc/skel/.config/UMS/UMS.conf
INFO  19:21:20.297 [main] Language not specified, defaulting to OS language.
ERROR 19:21:20.375 [main] Failed to write PID file: /root/.config/UMS/data/pms.pid (No such file or directory)
INFO  19:21:20.375 [main] Starting Universal Media Server 9.0.0
INFO  19:21:20.375 [main] Based on PS3 Media Server by shagrath, copyright 2008-2014
INFO  19:21:20.375 [main] https://www.universalmediaserver.com
INFO  19:21:20.375 [main] 
INFO  19:21:20.375 [main] Build: 43479db33 (2019-09-06)
INFO  19:21:20.375 [main] Java: OpenJDK 64-Bit Server VM 1.8.0_212 (64-bit) by IcedTea
INFO  19:21:20.376 [main] OS: Linux 64-bit 4.15.0-46-generic
INFO  19:21:20.380 [main] Maximum JVM Memory: 455.5 MiB
INFO  19:21:20.383 [main] Language: English (United States)
INFO  19:21:20.383 [main] Encoding: UTF-8
INFO  19:21:20.383 [main] 
INFO  19:21:20.383 [main] Working directory: /usr/src/ums
INFO  19:21:20.384 [main] Temporary directory: /tmp/UMS-root
INFO  19:21:20.384 [main] Logging configuration file: /usr/src/ums/logback.headless.xml
INFO  19:21:20.384 [main] Logfile: /var/log/UMS/root/debug.log
INFO  19:21:20.384 [main] 
INFO  19:21:20.384 [main] Profile directory: /root/.config/UMS
WARN  19:21:20.384 [main] Profile directory not found: File "/root/.config/UMS" not found
INFO  19:21:20.384 [main] Profile configuration file: /root/.config/UMS/UMS.conf
WARN  19:21:20.384 [main] Profile configuration file not found: File "/root/.config/UMS/UMS.conf" not found
INFO  19:21:20.386 [main] Profile name: tristan-home
INFO  19:21:20.386 [main] 
INFO  19:21:20.387 [main] Web configuration file: /root/.config/UMS/WEB.conf
WARN  19:21:20.387 [main] Web configuration file not found: File "/root/.config/UMS/WEB.conf" not found
INFO  19:21:20.387 [main] 
INFO  19:21:20.397 [main] Using database located at: "/root/.config/UMS/database"
INFO  19:21:20.594 [main] Graphics environment not available or headless mode is forced
INFO  19:21:20.594 [main] Switching to console mode
INFO  19:21:20.611 [main] Generated new random UUID: e08b824d-9836-4996-8db8-cdf6193661e5
INFO  19:21:20.614 [main] Configuration saved to "/root/.config/UMS/UMS.conf"
INFO  19:21:20.615 [main] Using the following UUID configured in UMS.conf: e08b824d-9836-4996-8db8-cdf6193661e5
INFO  19:21:20.640 [main] Loading MediaInfo library
INFO  19:21:20.656 [main] Loaded MediaInfoLib - v19.04
INFO  19:21:20.663 [main] Loading renderer configurations from /usr/src/ums/renderers
INFO  19:21:20.810 [main] Enabled 161 configurations, listed in order of loading priority:
INFO  19:21:20.810 [main] :   BubbleUPnP
INFO  19:21:20.810 [main] :   Chromecast
INFO  19:21:20.810 [main] :   Naim Mu-So
INFO  19:21:20.810 [main] :   Panasonic AS600
...
INFO  19:21:20.816 [main] :   Yamaha RX-V671
Sep 17, 2019 7:21:20 PM org.fourthline.cling.UpnpServiceImpl <init>
INFO: >>> Starting UPnP service...
Sep 17, 2019 7:21:20 PM org.fourthline.cling.UpnpServiceImpl <init>
INFO: Using configuration: net.pms.network.UPNPControl$1
Sep 17, 2019 7:21:20 PM org.fourthline.cling.transport.RouterImpl <init>
INFO: Creating Router: org.fourthline.cling.transport.RouterImpl
Sep 17, 2019 7:21:20 PM org.fourthline.cling.transport.impl.MulticastReceiverImpl init
INFO: Creating wildcard socket (for receiving multicast datagrams) on port: 1900
Sep 17, 2019 7:21:20 PM org.fourthline.cling.transport.impl.MulticastReceiverImpl init
INFO: Joining multicast group: /239.255.255.250:1900 on network interface: enp0s31f6
Sep 17, 2019 7:21:20 PM org.fourthline.cling.transport.impl.StreamServerImpl init
INFO: Created server (for receiving TCP streams) on: /192.168.1.103:35751
Sep 17, 2019 7:21:20 PM org.fourthline.cling.transport.impl.DatagramIOImpl init
INFO: Creating bound socket (for datagram input/output) on: /192.168.1.103
Sep 17, 2019 7:21:20 PM org.fourthline.cling.UpnpServiceImpl <init>
INFO: <<< UPnP service started successfully
INFO  19:21:20.861 [main] Checking the fontconfig cache in the background, this can take two minutes or so.
ERROR 19:21:20.883 [main] Error initializing process: 
INFO  19:21:20.884 [main] Configuration saved to "/root/.config/UMS/UMS.conf"
INFO  19:21:20.919 [main] Transcoding engine "FFmpeg Audio" is available
WARN  19:21:20.926 [main] Transcoding engine "MEncoder Video" is not available
INFO  19:21:20.926 [main] Transcoding engine "FFmpeg Video" is available
WARN  19:21:20.927 [main] Transcoding engine "VLC Video" is not available
INFO  19:21:20.960 [main] FFmpeg web filters "/root/.config/UMS/ffmpeg.webfilters" not found, web filters ignored
INFO  19:21:20.961 [main] Transcoding engine "FFmpeg Web Video" is available
WARN  19:21:20.961 [main] Transcoding engine "MEncoder Web Video" is not available
WARN  19:21:20.961 [main] Transcoding engine "VLC Web Video" is not available
WARN  19:21:20.963 [main] Transcoding engine "tsMuxeR Video" is not available
WARN  19:21:20.963 [main] Transcoding engine "tsMuxeR Audio" is not available
WARN  19:21:20.963 [main] Transcoding engine "VLC Web Audio (Legacy)" is not available
WARN  19:21:20.963 [main] Transcoding engine "VLC Web Video (Legacy)" is not available
WARN  19:21:20.964 [main] Transcoding engine "DCRaw" is not available
INFO  19:21:20.965 [main] Using address /172.17.0.1 found on network interface: name:docker0 (docker0)
INFO  19:21:20.965 [main] Created socket: /172.17.0.1:5001
INFO  19:21:21.013 [main] WEB interface is available at: http://172.17.0.1:9001
INFO  19:21:21.029 [main] A tiny cache admin interface is available at: http://172.17.0.1:5001/console/home
INFO  19:21:23.651 [main] Universal Media Server is now available for renderers to find
INFO  19:21:38.126 [pool-1-thread-1] Checking shared folder: "/usr/src/ums"
INFO  19:21:38.126 [pool-1-thread-1] Checking shared folder: "/root"
``` 
I visited http://172.17.0.1:9001 and can't see any file.Is that correct? How could i set the sharing folder?

**Comment by atamariya** [comment]
You don't need to use sudo.

**Comment by tr15tan** [comment]
> You don't need to use sudo.

Oh, I didn't add my user account to the docker group so I would get errors without sudo prefix. Does this impact the working of ums?

**Comment by atamariya** [comment]
Ok, I checked again - sudo shouldn't be a problem. Just change the volume though. Following works for me.
` sudo docker run -it --net host  -v ~/Music:/root universalmediaserver/ums
`

**Comment by tr15tan** [comment]
> Ok, I checked again - sudo shouldn't be a problem. Just change the volume though. Following works for me.
> `sudo docker run -it --net host -v ~/Music:/root universalmediaserver/ums`
> After the first run, you can find your UMS.conf file at Music/.config/UMS/ .

It seems that the path after `-v` represents the resource directory? I don't know why should i use `:/root` but after change `~/Music` to the path of my video directory, it worked: some of my videos can be seen in the browser, however, some still not, even they are in the same format. 

There is one more problem, i can still not find these resources in my PS4 with the MediaPlayer App, and the same network environment worked in my windows10 system. Well, i tried vlc app in my phone(android 7.0 os), and can't find resources in the `Local Network` folder neither. What should i do to check what is going on? Let me know if you need any log files, thanks.

**Comment by atamariya** [comment]
Did you check your firewall? You need to enable incoming connections on 1900/udp, 9001 and 5001.

**Comment by jsburckhardt** [comment]
based on the new code updates I could make it run pushing the configs/media directly to root user
`docker run -it -p 1044:1044 -p 5002:5002 -p 9001:9001 -v <path to media folder>:/root/media -v <path to folder that contains the UMS.config file>:/root/.config/UMS universalmediaserver/ums` 
For example:
`docker run -it -p 1044:1044 -p 5002:5002 -p 9001:9001 -v /home/ubuntu/repos/services/ums/media/:/root/media -v /home/ubuntu/repos/services/ums/profile/:/root/.config/UMS universalmediaserver/ums`
my folder structure:
.
├── media
│   ├── movie1.mp4
│   └── movie2.mp4
└── profile
|    └── UMS.conf

Hope we get some doco soon. thanks

**Comment by wegotshrimp** [comment]
You may also need to set the hostname/network interface parameter for proper discovery, I was having the issue where it would bind to the wrong interface and wasn't being seen on the network. I ended up just using net=host for this.

As a side note, has anyone gotten mencoder to work in the docker image? It doesn't come with it at all, but I wonder if you could compile it in alpine.

**Comment by SubJunk** [comment]
@wegotshrimp I have been unsuccessful at compiling a static version of MEncoder for Linux in the past after spending a long time trying. If you have any success with that we would love the contribution!

**Comment by TheQue42** [comment]
Is there still no better docs on how to use UMS in docker?? Why even supply a docker image, if there is no docs on how to use it?

Even running with --network=host and --privileged, i end up with a line saying:

"ERROR 07:45:18.956 [main] A serious error occurred during Universal Media Server initialization: null"

**Comment by SubJunk** [comment]
@TheQue42 thanks for letting us know about this, that is a bug with the recent release on headless environments. I will release a fix today and let you know when it's pushed to Docker Hub.

**Comment by SubJunk** [comment]
@TheQue42  that should be fixed now, please let me know if there are any other problems

**Comment by SubJunk** [comment]
Also about the docs situation, maybe you can help us with that. We are open source so we rely on contributions

**Comment by SubJunk** [comment]
Closing this because it seems to be working well for many people. More questions can always have new issues or discussions.

**Comment by heater19** [comment]
I would like help in installing UMS on an openmediavault server;

In short, when i run the web interface at the port :9001, i'm not seeing the directory for my videos and I'm not seeing the media server on the PS3;

Thanks in advance;

the details are below::::::::::::::::::  👇 

the installation was done via portainer with the following settings:

image: universalmediaserver/ums:latest

added 3 ports - 1044, 5002 and 9001, all are TCP;

then I added 2 volumes:

the container is labeled - /media with the 'bind' option set, the path is set to '/srv/dev-disk-by-uuid-31265/Videos', which is then set to writable;

the second container is labeled - /profile with the 'bind' option set, the path is set to '/srv/dev-disk-by-uuid-31265/Config', which is then set to writable;

the environment variables are the following:
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
JVM_OPTS=-Xmx512M

Restart policy is 'unless stopped'

everything else was left with the default settings;

::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

**Comment by Pysis868** [comment]
Where should the docs be added?  In what format?  Let's get it started, and can always improve it over time.

Also, my docker headless installation is still having issues.  Should we really create a new post for it?  Having a single one amongst many for this 1 install type seems convenient.

**Comment by SubJunk** [comment]
@Pysis868 docs should ideally be added to https://support.universalmediaserver.com/
If you are interested in that I can add you, I'll need an email address to invite. You can message it to me on our forum if you want it kept private

**Comment by Pysis868** [comment]
I can take a look, just thinking about reducing the effort needed to finally get some docs added for this pathway. I would probably mostly just add the main `pull` command and the `run` one from this thread, even if I don't have it working myself yet, although my environment may be different enough to cause some problems.

**Comment by SubJunk** [comment]
Great, any help at all is greatly appreciated! I have had a goal for a long time to integrate our docs into one place, since they have historically had many different places, which is confusing. My dream is to link everything to that support subdomain when it has more content.

**Comment by Pysis868** [comment]
Added https://support.universalmediaserver.com/books/installation/page/docker.

**Comment by leranp** [comment]
Tried to run the docker without "network_mode: host" but there is an error with the UPnP
'''
ums  | INFO  15:27:32.765 [main] Starting UPnP service...
ums  | ERROR 15:27:32.807 [main] Unable to initialize network router: org.jupnp.transport.spi.InitializationException: Could not initialize UmsMulticastReceiver: java.net.BindException: Address in use
ums  | ERROR 15:27:32.808 [main] Cause: org.jupnp.transport.spi.InitializationException: Could not initialize UmsMulticastReceiver: java.net.BindException: Address in use
ums  | ERROR 15:27:32.811 [main] FATAL ERROR: Unable to start upnp service
'''
Without the "network_mode: host" the upnp looks like it is running but the Samsung TV doesn't see the service

**Comment by Pysis868** [comment]
Added some Debian instructions and tested them a bit, but it's mostly what Docker, and is specific for the container, already has in each of those help documents.

**Comment by Mik-S-UMS** [comment]
There have been a few users on the forum that have had problems with installing UMS in docker recently. I was not much help as know almost nothing about it but one wrote a [guide](https://www.universalmediaserver.com/forum/viewtopic.php?p=47952) that may be helpful which is based on an old thread [here](https://www.universalmediaserver.com/forum/viewtopic.php?t=12922)

They also mentioned there are problems with the docker image of UMS that they have to work around. 
One thing I noticed was reference to WEB.conf which is no longer used. If I understand this `wget` loop bit it retrieves these 3 files but should this not be necessary as they will be created with defaults when UMS starts?

Apparently the SHARED.conf in the image has the config folder shared which causes UMS to try and parse and add the database to the database whenever it is updated. This may have been user error though due to unclear instructions.

Can the Docker image be updated so these work-arounds are not needed anymore?

**Comment by SubJunk** [comment]
@Pysis868 thank you, I have merged that documentation update now

@Mik-S-UMS unfortunately I don't know much about how the Docker image works either, it's something I continue to release  but I haven't had much to do with it. I'm very happy for any more contributions from anyone

**Comment by Pysis868** [comment]
I've removed the manual file downloads (https://github.com/UniversalMediaServer/knowledge-base/pull/36) since the ff one is the same, and the WEB one does not exist in the GH repo now.  Just remains that the `UMS.conf` file be updated now.
I see the `Dockerfile` copies from some host directory to create the image, so maybe that needs an admin to process that since I did see differences between the default file and the downloaded one.
I also see the `build.xml` mentioning the docker build if that is helpful, but not something for me to do.

Is there anything else notable to fix instead of vague posts to old forum information?  I couldn't test an actual video after following the instructions for my Fedora Linux 39 system since it kept encountering an error during start and exiting with the `libwebp-imageio.so` library, `UpsampleBgraLinePair_SSE2` function, `OpenJDK Runtime Environment (17.0.9+8)`.
