### ISSUE TITLE
Unable to play audio from web interface

### ISSUE THREAD

**Issue by derekjax** [UniversalMediaServer/UniversalMediaServer#3130]
I had installed UMS on my last computer, and it worked perfectly. That computer died, I got a new one and have been trying to get UMS set up but am having an issue. The program is installed, I added my iTunes, music, and video folders, and the program went through scanning the folders. When I go to the web interface now, I can see all my music and videos there, but either one of two things happen: 
1) most of the audio files open up with album artwork, and a big white X in the middle, and there's an error message across the top of the artwork that says: "The media could not be loaded, either because the server or network failed or because the format is not supported." These are itunes files, so the file format should be either mpg or m4a, which I thought were both supported by UMS. (And worked perfectly on my last computer, though that was the last version of UMS 10.something. I'm on the new 11.1.0 version now.) 
2) some of the audio files will open up with album artwork, and show the play button, progress bar and volume slider, but the file will not play. No error messages appear, just nothing happens at all. 

When UMS was first going through scanning all of my folders, I noticed it kept putting an error message into the logs. I didn't know exactly what it meant, and of course the messages are long gone, but I thought it was something about the artwork, and it had a website and 503. I had assumed it was just not able to find the albums, and thus wasn't able to get the artwork. I didn't think it would cause an issue in being able to play the files. 
Also, in the current logs, it keeps saying that it can't find the itunes file. I am assuming this is the itunes library.xml file? I don't see anywhere to point UMS to that file location, though I don't know why it can't find it - it's in the itunes directory. 
Any help is appreciated. Thanks

**Comment by SubJunk** [comment]
@derekjax I think this is fixed in the upcoming update which should be released within the next few days

**Comment by derekjax** [comment]
Oh okay, good to know - thanks! I did try uninstalling 11.1.0 and reinstalled the old version which I still had the install file for (10.8.2) hoping that it would work, but I couldn't get it to scan for my media in the files I designated. I tried restarting the server a few times hoping to prompt it into scanning the files but it didn't. So I'll just uninstall everything and wait for the new version to drop. 
thanks again

**Comment by SubJunk** [comment]
I'll attach a link to a preview version if you let me know your OS?

**Comment by derekjax** [comment]
Thanks!
Win 11

**Comment by SubJunk** [comment]
https://www.universalmediaserver.com/uploads/UMS-derekjax.exe
Please let me know when you have downloaded it and if it fixed your problem

**Comment by derekjax** [comment]
Thanks for the file. It does seem to have worked for my audio files. The
app installed and I can now access my audio files through the web
interface. Unfortunately, it has not worked for videos. I still get " The
media could not be loaded, either because the server or network failed or
because the format is not supported." when I try to play videos online.
(When I try to play a video and get this message, I note that there is no
entry added to the log file.)

There are a couple of other things I would point out.
1) After I installed the program and selected my media folders, the app
doesn't automatically start scanning for files - and I can't find an option
to manually initiate a scan of my folders. Even upon restarting the app, it
still wouldn't do the very first scan of my folders. I had to check the
'automatically scan' box and restart the app for it to even do the first
scan. Not a huge problem, but if someone is new to the app, they definitely
won't know that work around.
2) The log is still showing the error "Could not find the iTunes file". (I
checked the "Show itunes library" box) I know my itunes library.xml file is
in the itunes folder (which is listed as one of my shared folders), so I'm
not sure why it can't find it, but I also do not see a way to manually
point the app to the file location.
3) I am also still seeing a lot of this error message: "Could not lookup
audio cover for "Paperback Writer": musicbrainz.org replied with status
code 503" I had assumed "audio cover" is referring to the artwork, and this
website doesn't have the artwork for UMS to grab? Or is that error about
something else?
4) To go along with not being able to play videos, I am seeing the
following errors in the debug.log file. This is just one example, but it
looks like all the videos are saying the same thing. Is this saying there's
something wrong with the transcoder, and that it can't play mp4 files? FTR,
I did not have any problem accessing videos when I was using the older
version on my previous computer. So I'm not sure what's causing the issue.
I can tell you that I did try playing videos on the 11.1.0 version I had
briefly installed, and was able to play a couple successfully, though only
a few worked then. Now no videos will play.

TRACE 2022-07-03 08:25:16.294 [pool-6-thread-9]
net.pms.formats.FormatFactory Matched format MPG to "E:\iTunes\Music\Elvis
Presley\Unknown Album\Blue Christmas.m4v"
TRACE 2022-07-03 08:25:16.295 [pool-6-thread-9] net.pms.util.SubtitleUtils
Searching for external subtitles for Blue Christmas.m4v
TRACE 2022-07-03 08:25:16.297 [pool-6-thread-9]
net.pms.database.MediaTableThumbnails Searching for thumbnail in THUMBNAILS
with "SELECT ID FROM THUMBNAILS WHERE MD5 =
'd4ed8a404822e8cfbe362cd2d58ca2b0' LIMIT 1" before update
TRACE 2022-07-03 08:25:16.297 [pool-6-thread-9]
net.pms.database.MediaTableThumbnails Found existing thumbnail with ID 994
in THUMBNAILS, setting the THUMBID in the FILES table
TRACE 2022-07-03 08:25:16.297 [pool-6-thread-9]
net.pms.database.MediaTableFiles THUMBID updated to 994 for
E:\iTunes\Music\Elvis Presley\Unknown Album\Blue Christmas.m4v
TRACE 2022-07-03 08:25:16.298 [pool-6-thread-9] net.pms.dlna.DLNAResource
Adding new child "Blue Christmas.m4v" with class "RealFile"
TRACE 2022-07-03 08:25:16.298 [pool-6-thread-9]
net.pms.formats.FormatFactory Getting player for resource "Blue
Christmas.m4v"
TRACE 2022-07-03 08:25:16.298 [pool-6-thread-9]
net.pms.formats.FormatFactory Returning compatible player "FFmpeg Video"
TRACE 2022-07-03 08:25:16.298 [pool-6-thread-9]
net.pms.configuration.FormatConfiguration Format "mp4" failed to match
supported line f:mpegts v:h264
a:aac-lc|aac-ltp|aac-main|aac-ssr|he-aac|ac3|eac3 m:video/mp2t
TRACE 2022-07-03 08:25:16.298 [pool-6-thread-9]
net.pms.configuration.FormatConfiguration Format "mp4" failed to match
supported line f:flv v:h264|hls a:aac-lc m:video/flash
TRACE 2022-07-03 08:25:16.298 [pool-6-thread-9]
net.pms.configuration.FormatConfiguration Matched support line f:mp4
m:video/mp4
DEBUG 2022-07-03 08:25:16.298 [pool-6-thread-9] net.pms.dlna.DLNAResource
Final verdict: "Blue Christmas.m4v" will be streamed
TRACE 2022-07-03 08:25:16.298 [pool-6-thread-9]
net.pms.configuration.FormatConfiguration Format "mp4" failed to match
supported line f:mpegts v:h264
a:aac-lc|aac-ltp|aac-main|aac-ssr|he-aac|ac3|eac3 m:video/mp2t
TRACE 2022-07-03 08:25:16.298 [pool-6-thread-9]
net.pms.configuration.FormatConfiguration Format "mp4" failed to match
supported line f:flv v:h264|hls a:aac-lc m:video/flash
TRACE 2022-07-03 08:25:16.298 [pool-6-thread-9]
net.pms.configuration.FormatConfiguration Matched support line f:mp4
m:video/mp4
TRACE 2022-07-03 08:25:16.298 [pool-6-thread-9] net.pms.dlna.DLNAResource
File "Blue Christmas.m4v" will be sent with MIME type "video/mp4"
TRACE 2022-07-03 08:25:16.298 [pool-6-thread-9] net.pms.dlna.DLNAResource
Adding "Blue Christmas.m4v" to transcode folder for player: "null"



I meant to pack the trace log files but I restarted the app because it had
hung up for a long time while scanning one folder and I was trying to nudge
it on and forgot to pack the files before shutting it down. I did have the
debug.log file open, so I was able to save that, and I've restarted the
trace logs. I'm attaching that first debug.log file separately, and the
packed debug files, so hopefully this will shed some light on what's going
on.

Thanks again for your help, and I hope this all helps!
 debug.log
<https://drive.google.com/file/d/1joaQaw_fqAtU3lJa271tARHwavX1W3cR/view?usp=drive_web>
 ums_dbg_2022-07-03-18-45.zip
<https://drive.google.com/file/d/1faOrGC8HGt0G1XDMVcFeXKoTMR8TPwep/view?usp=drive_web>

**Comment by derekjax** [comment]
> https://www.universalmediaserver.com/uploads/UMS-derekjax.exe Please let me know when you have downloaded it and if it fixed your problem

Any thoughts on what the issue could be?

**Comment by DiegoBM** [comment]
I can confirm that audio won't play on web interface for UMS windows neither on v12 nor v13. When you navigate to the song no player will be displayed neither on Chrome nor Edge browsers. Video and pictures work fine though. Logs don't seem to display any errores besides the invalid value 30 for parameter parameterIndex already reported

**Comment by SubJunk** [comment]
This should be fixed in the next release. If you let me know which operating system you're on @DiegoBM  I can upload a fixed build

**Comment by DiegoBM** [comment]
Thanks @SubJunk, I use Windows 11, but I was considering setting up a server on a raspberry pi 3

**Comment by SubJunk** [comment]
@DiegoBM sorry I forgot to upload that fix, I think it's in the latest release now

**Comment by DiegoBM** [comment]
Hi @SubJunk, I've tried the 13.0.1 version which is the latest one I can see in github, and the problem still remains there

**Comment by SubJunk** [comment]
Can you let me know if this one works? https://www.universalmediaserver.com/uploads/UMS-3130.exe

**Comment by DiegoBM** [comment]
This one seems to work fine :)

**Comment by SubJunk** [comment]
Thanks for confirming :D
