### ISSUE TITLE
v14.0 release.  Issue with root directory drive scan

### ISSUE THREAD

**Issue by radioresearch** [UniversalMediaServer/UniversalMediaServer#4653]
I am getting these errors in the logfile when UMS scans the disks for content.
 ERROR A plugin has attempted to add a null child to "root"

Hence, the directory scan only includes films under a directory "to be seen" and not the other three disks full of films.
This has never happened before with any other version.  It has only now occurred after upgrading to the v14.0 sent from the Patreon site.
On the three disks in question, all film directories are in the root directory and not in a subdirectory.

I hope someone can help me with this.  Thanks!!

[ums_dbg_2024-05-14-09-23.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/15308987/ums_dbg_2024-05-14-09-23.zip)

**Comment by SurfaceS** [comment]
`AccessDeniedException: D:\System Volume Information`

fixed on #4654

**Comment by SubJunk** [comment]
@radioresearch thanks for reporting this, I will upload the fixed version for you

**Comment by SubJunk** [comment]
That's done at https://www.patreon.com/posts/v14-quick-fixes-104283462

**Comment by SubJunk** [comment]
@radioresearch I swapped out the file on Patreon with the second attempt at a fix, please let us know how it goes

**Comment by radioresearch** [comment]
@SubJunk  I'm sorry to report that there is no change.  It's still the same issue.  Logs attached.
[ums_dbg_2024-05-16-06-51.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/15334004/ums_dbg_2024-05-16-06-51.zip)

**Comment by SurfaceS** [comment]
@radioresearch 
can you browse (with web player and upnp) to see what it serve ?
something like browse root, then D:\ if it exists

**Comment by radioresearch** [comment]
@SurfaceS   No, I am unable to see into any of the drives E:, F:, or G:,.  Those drives are all filled with movies in the root directory.  This was all working with earlier versions.  It does not show via browser, and the browser simply shows what is in the application control panel.  I mostly use this with my TV, so I really don't use the browser extension that much.  Is it possible that thev14 release simply will not look into the root of a disk?  That would seem a likely explanation.

**Comment by SurfaceS** [comment]
@radioresearch 
I added more log in my last PR.
You should wait for @SubJunk to upload that version for you, then we may have more info about this.

A quick question :
Did your roots drives E:, F:, or G: have hidden attribute ?
If so, you may have to remove this attribute.

**Comment by radioresearch** [comment]
@SurfaceS  Hi, no my drives do not have a hidden attribute.  Thanks for all your help!

**Comment by SubJunk** [comment]
I can make the new build when I'm home from work in about 11 hours

**Comment by SubJunk** [comment]
@radioresearch I have replaced the Patreon file again with the new logging one we need, this time it is `UMS-9f2b752.exe`

**Comment by radioresearch** [comment]
@SubJunk Attached are the debug files using your new executable.  Thanks again.
[ums_dbg_2024-05-17-06-44.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/15347943/ums_dbg_2024-05-17-06-44.zip)

**Comment by SurfaceS** [comment]
@radioresearch
Strangely, in java point of view, `D:\`, `E:\` and `G:\` are hidden.
```
TRACE 2024-05-17 06:41:41.053 [Media Scanner] net.pms.store.MediaStore createResourceFromFile return null as  is hidden.
TRACE 2024-05-17 06:41:41.053 [Media Scanner] net.pms.store.MediaStore createResourceFromFile has failed for D:\
TRACE 2024-05-17 06:41:41.053 [Media Scanner] net.pms.store.MediaStore createResourceFromFile return null as  is hidden.
TRACE 2024-05-17 06:41:41.053 [Media Scanner] net.pms.store.MediaStore createResourceFromFile has failed for E:\
TRACE 2024-05-17 06:41:41.053 [Media Scanner] net.pms.store.MediaStore createResourceFromFile return null as  is hidden.
TRACE 2024-05-17 06:41:41.053 [Media Scanner] net.pms.store.MediaStore createResourceFromFile has failed for G:\
```

**Comment by radioresearch** [comment]
@SubJunk 
I am at a complete loss as to why this is happening.  The Java is the latest version, and there no settings inside Java pertinent to disk access.  The disks in question are shared out completely at the root directory (can be accessed/full control) across my home network.  Everything was working fine until I installed 14.0.0 and thereafter this happened.
I am not a programmer.  I'm a network guy, but if there are any suggestions you have that I could do to the server, I'll gladly try them.  Thanks yet again!

**Comment by SurfaceS** [comment]
@radioresearch
I posted a fix to allow hidden roots shared content.

You should wait for @SubJunk to upload that version for you to test.

**Comment by SubJunk** [comment]
@SurfaceS thanks, I will build that today, probably within the next 2 hours

**Comment by SubJunk** [comment]
@radioresearch that's on Patreon

**Comment by radioresearch** [comment]
@SubJunk @SurfaceS 

Gentlemen!!  That fixed it!  Thank you so much!  Let me know if you want me to submit the logs again.

**Comment by SubJunk** [comment]
@radioresearch excellent, thank you for confirming that! hope you enjoy
